version: "3"

services:
  dotsmesh-host-nginx:
    image: dotsmesh/dotsmesh-host-nginx
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    networks:
      - dotsmesh-network
    volumes:
      - ${HOME_VOLUME}:/dotsmesh-home
      - ${CERTIFICATES_VOLUME}:/dotsmesh-certificates
    depends_on:
      - dotsmesh-host-php
    restart: always
    environment:
      - HOST

  dotsmesh-host-certbot:
    image: dotsmesh/dotsmesh-host-certbot
    volumes:
      - ${HOME_VOLUME}:/dotsmesh-home
      - ${CERTIFICATES_VOLUME}:/dotsmesh-certificates
    depends_on:
      - dotsmesh-host-nginx
    restart: always
    environment:
      - HOST
      - CERTIFICATE_EMAIL

  dotsmesh-host-php:
    image: dotsmesh/dotsmesh-host-php
    networks:
      - dotsmesh-network
    volumes:
      - ${HOME_VOLUME}:/dotsmesh-home
    restart: always

networks:
  dotsmesh-network:
